# Generated by Django 5.2.7 on 2025-10-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloginfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=40)),
                ('vehicle', models.CharField(max_length=40)),
                ('friends', models.CharField(max_length=40)),
            ],
        ),
    ]
