# Generated by Django 5.2.7 on 2025-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.IntegerField()),
                ('customerName', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=13)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
