# Generated by Django 5.2.7 on 2025-10-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewelry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='product',
        ),
    ]
