# Generated by Django 5.2.7 on 2025-11-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jewelry', '0002_remove_productinfo_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
