# Generated by Django 5.2.7 on 2025-10-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Man_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField()),
                ('personName', models.CharField(max_length=40)),
                ('phoneNumber', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('productName', models.CharField(max_length=40)),
            ],
        ),
    ]
