# Generated by Django 5.2.7 on 2025-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('payment', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=55)),
                ('quantity', models.CharField(max_length=10)),
            ],
        ),
    ]
