# Generated by Django 6.1 on 2026-09-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cart_order_product_orderitem_review_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bkash_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='bkash', max_length=20),
        ),
    ]
